<?php
/**
 * SDK Configuration
 *
 * Defines the API base URL, product ID, and the product-level API key/secret
 * used for HMAC-SHA256 request signing.
 * 
 * IMPORTANT: This file is AUTO-GENERATED by the SI License Manager Developer Tools.
 * Do not hand-edit this file. If the product's API key is rotated, regenerate
 * and redistribute this file via the SDK Generator.
 *
 * @package SICSAP\Premium\SDK
 */

declare(strict_types=1);

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * 1. API Base URL
 * The root endpoint for the SI License Manager REST API.
 * All licensing endpoints live under the /si-license-manager/v1/ namespace.
 */
if ( ! defined( 'SI_SDK_API_BASE_URL' ) ) {
    define( 'SI_SDK_API_BASE_URL', 'https://your-domain.com/wp-json/si-license-manager/v1' );
}

/**
 * 2. Product Identifier
 * The unique slug/ID for this specific product in the License Manager.
 */
if ( ! defined( 'SI_SDK_PRODUCT_ID' ) ) {
    define( 'SI_SDK_PRODUCT_ID', 'si-case-study-analysis-pro' );
}

/**
 * 3. Product API Key & Secret
 * This key identifies the PRODUCT, not the customer. 
 * It is bundled into the distributed plugin and doubles as the HMAC signing secret.
 * It is NEVER a customer's license key.
 */
if ( ! defined( 'SI_SDK_API_KEY' ) ) {
    define( 'SI_SDK_API_KEY', 'pk_live_REPLACE_WITH_YOUR_PRODUCT_API_KEY' );
}

if ( ! defined( 'SI_SDK_API_SECRET' ) ) {
    define( 'SI_SDK_API_SECRET', 'sk_live_REPLACE_WITH_YOUR_PRODUCT_API_SECRET' );
}

/**
 * 4. SDK Version & Timeouts
 * Configuration for HTTP request handling and cache durations.
 */
if ( ! defined( 'SI_SDK_TIMEOUT' ) ) {
    define( 'SI_SDK_TIMEOUT', 15 ); // Seconds
}

if ( ! defined( 'SI_SDK_VERIFY_CACHE_TTL' ) ) {
    define( 'SI_SDK_VERIFY_CACHE_TTL', HOUR_IN_SECONDS ); // Cache verification results for ~1 hour
}